apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: nginx-deployment
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-pod
    spec:
      volumes:
        - name: nginx-config-directory
          configMap:
            name: nginx-config-directory
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: {{ .Values.deployment.httpPort }}
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-config-directory
