apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: nginx-pod
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.svc.port }}
      targetPort: {{ .Values.deployment.httpPort }}
      nodePort: {{ .Values.svc.nodePort }}
